### ISSUE TITLE
The Tutorial doesnt show a circle around the view as is its shown the demo gif

### ISSUE THREAD

**Issue by iAviatorJose** [itzikBraun/TutorialView#10]
Hi @itzikBraun i developed sample app to see how your libray works.

I have a textview with text "Hello World" and i tried it with your library to describe its purpose.
The Tutorial got generated but the View was not surrounded/Higlighted by another view.
Below is a link to the image describing the issue. 

![device-2015-08-11-121348](https://cloud.githubusercontent.com/assets/8208627/9191864/b7729a1e-4023-11e5-8083-23104cb57dc4.png)

I used the following code.
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
         tv1 = (TextView)findViewById(R.id.tv_msg);
         tv2 = (TextView)findViewById(R.id.tv_msg_2);

```
    TutorialIntentBuilder builder = new TutorialIntentBuilder(MainActivity.this);
    TutorialBuilder builder1 = new TutorialBuilder();
    builder.changeSystemUiColor(false);
    builder1.setTitle("The Title")
            .setViewToSurround(tv1)
            .setInfoText("This is the explanation about the view.")
            .setBackgroundColor(Color.parseColor("#aa000000"))
            .setTutorialTextColor(Color.WHITE)
            .setTutorialTextTypeFaceName("fonts/roboto_light.ttf")
            .setTutorialTextSize(25)
            .setAnimationDuration(500);
    TutorialBuilder builder2 = new TutorialBuilder();

    builder2.setTitle("The Title")
            .setViewToSurround(tv2)
            .setInfoText("This is the explanation about the view.")
            .setBackgroundColor(Color.parseColor("#aa000000"))
            .setTutorialTextColor(Color.RED)
            .setTutorialTextTypeFaceName("fonts/roboto_light.ttf")
            .setTutorialTextSize(25)
            .setAnimationDuration(500);

    tutorials.add(builder1.build());
    tutorials.add(builder2.build());

    builder.skipTutorialOnBackPressed(true);
    builder.setWalkThroughList(tutorials);
    startActivity(builder.getIntent());
    //        builder.setTutorial(tBuilder.build());
```

//        startActivity(builder.getIntent());
    }

**Comment by itzikBraun** [comment]
Hi,

Where do you call your start activity? Can you try to call it after the window have focus and let me know if it helped, This behaviour is not the usual behaviour when you call start activity to early but it might be the problem.

You can call it from on click or in onWindowFocusChanged.

**Comment by iAviatorJose** [comment]
@itzikBraun  I had call startActivity inside onCreate() and now when i tried it inside onWindowFocusChanged() The Circle did get created but the Walkthrough list that i had set got created multiple times.

**Comment by iAviatorJose** [comment]
@itzikBraun i checked for savedInstance == null and then started the walkthrough and it worked Properly, There is one more thing i would like to know can even the ActionBarItems also be Highlighted. 

# I tried the following code, and i was unsuccessful at it. inside onOptionsItemSelected.

  @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

```
    //noinspection SimplifiableIfStatement
    if (id == R.id.action_settings) {
        TextView settings = (TextView)item.getActionView();
        TutorialIntentBuilder builder = new TutorialIntentBuilder(MainActivity.this);

        // if true the status bar and navigation bar will be colored on Lollipop devices.
```

//            builder.changeSystemUiColor(true);

```
        TutorialBuilder tBuilder = getBasicBuilderForTest(settings);
        tBuilder.setTutorialInfoTextPosition(Tutorial.InfoPosition.LEFT_OF);
        builder.setTutorial(tBuilder.build());
        startActivity(builder.getIntent());
        return true;
    }

    return super.onOptionsItemSelected(item);
}
```

 private TutorialBuilder getBasicBuilderForTest(View v){
        TutorialBuilder tBuilder = new TutorialBuilder();

```
    tBuilder.setTitle("The Title")
            .setViewToSurround(v)
            .setInfoText("This is the explanation about the view.")
            .setBackgroundColor(Color.parseColor("#aa000000"))
            .setTutorialTextColor(Color.WHITE)
            .setTutorialTextTypeFaceName("fonts/roboto_light.ttf")
            .setTutorialTextSize(30)
            .setAnimationDuration(500);

    return tBuilder;
}
```

---

And the app crashed with following stacktrace:
08-12 12:08:58.234    3327-3327/thesampletutorialmode.aviator.com.thesampletutorialmode E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: thesampletutorialmode.aviator.com.thesampletutorialmode, PID: 3327
    java.lang.IllegalArgumentException: You need to init all view position and dimensions or just use the setViewToSurround
            at com.braunster.tutorialview.object.TutorialBuilder.build(TutorialBuilder.java:184)
            at thesampletutorialmode.aviator.com.thesampletutorialmode.MainActivity.onOptionsItemSelected(MainActivity.java:139)
            at android.app.Activity.onMenuItemSelected(Activity.java:2760)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:541)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:4651)
            at android.view.View$PerformClick.run(View.java:19310)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by itzikBraun** [comment]
I can test it right now, But my guess is that the view you get from the item is null. I think that the view in the return from `getActionView()`is the view you set in `setActionView(View v)`

I will be able to test with you starting from Monday, But i will try to be available.

**Comment by iAviatorJose** [comment]
@itzikBraun i understood where the issue was. It was in the XML of the menu item, there i had not set a value for the attribute app:actionViewClass .

This is what i did 

 <item android:id="@+id/action_logout"
        android:title="Logout"
        android:icon="@drawable/logout_small"
        android:orderInCategory="101"
        app:actionViewClass="android.widget.ImageView"
        app:showAsAction="always" />

And inside OnCreateOptionMenu i wrote the following code:
 public boolean onCreateOptionsMenu(Menu menu) {
getMenuInflater().inflate(R.menu.master_grid_screen, menu);
        float density = getResources().getDisplayMetrics().density;
        int padding = (int)(5 \* density);
        //OnCallCheckIn
        MenuItem onCallItem = menu.getItem(0);
        mOnCallCheckIn = (ImageView)onCallItem.getActionView();
        mOnCallCheckIn.setPadding(padding,padding,padding,padding);
        mOnCallCheckIn.setImageDrawable(getResources().getDrawable(R.drawable.call));
 mOnCallCheckIn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

```
                TutorialIntentBuilder builder = new TutorialIntentBuilder(MasterGrid.this);
                editor.putBoolean("is_oncall_tutorial_viewed",true);
                editor.commit();
                // if true the status bar and navigation bar will be colored on Lollipop devices.
                builder.changeSystemUiColor(true);
                TutorialBuilder tBuilder = getBasicBuilderForTest(v,"","On Call Orders : \nClick here to place an order received by a phone call");
                tBuilder.setTutorialInfoTextPosition(Tutorial.InfoPosition.BELOW);
                tBuilder.setTutorialGotItPosition(Tutorial.GotItPosition.BOTTOM);
                builder.setTutorial(tBuilder.build());
                startActivity(builder.getIntent());
 }});
```

}
Hence i close this issue.
