### ISSUE TITLE
publishing the library on a repo

### ISSUE THREAD

**Issue by emanuelet** [itzikBraun/TutorialView#5]
Hi, 
would it be possible to publish the library on some repo of your choice (doesn't have to necessarly to be Maven Central)?
So far, I've been able to grab it via jitpack

```
https://jitpack.io/#itzikBraun/TutorialView/72d07059a9
```

That for sure would simplify a lot the update process to a new version.

P.S.: the library is awesome!

**Comment by itzikBraun** [comment]
Hi, 

I will add it to my todo list, I think maven is a great choice, but I have never uploaded a repo to their site so it might take some time. Hoping to get it done for the next version.

Thanks for the feedback and the kind words.

**Comment by jitpack-io** [comment]
Hi all

It would help a bit if there was a GitHub release of TutorialView https://github.com/itzikBraun/TutorialView/releases. That would create a version which can be specified in JitPack.

**Comment by itzikBraun** [comment]
@jitpack-io Added.

**Comment by jitpack-io** [comment]
:+1: Works like a charm! https://jitpack.io/#itzikBraun/TutorialView/0.8.1

**Comment by itzikBraun** [comment]
Project is now on maven central, And could be added like this:

```
dependencies{ 
    compile 'com.github.itzikbraun:TutorialView:0.8.1' 
}
```
