### ISSUE TITLE
Gradle Dependencies

### ISSUE THREAD

**Issue by ajtoms** [itzikBraun/TutorialView#7]
Hey, I'm working in Android Studio and I would like to try using your library for a project I'm working on, but my limited knowledge of gradle and maven and stuff is getting in my way for importing it. Every library I've used so far was imported by putting a line:

compile '<groupId>:<artifactId>:<version>'

in my build.gradle file. Is that doable with your library?

**Comment by itzikBraun** [comment]
Hi,

The compile 'groupId:artifact:version' is for loading a maven dependency from a central repository, I am working on adding the library to maven central so it would be easy to add to your project. 

Until then you can import the TutorialView module to you existing project using the AndroidStudio import module. After the module was imported you can add a dependency on it using compile project(':module_name').

You can open the gradle.build file in the app module and see how I did it there.

Let me know if you have more questions.

**Comment by jitpack-io** [comment]
Btw, it is also available as a Gradle dependency on JitPack https://jitpack.io/#itzikBraun/TutorialView/0.8.1
Import instructions are there as well.

**Comment by itzikBraun** [comment]
@jitpack-io  Thanks for adding that fact, Do you have a badge that I can add to my README.md file?

**Comment by jitpack-io** [comment]
Yes, here it is 
[![Release](https://img.shields.io/github/release/itzikBraun/TutorialView.svg?label=JitPack)](https://jitpack.io/#itzikBraun/TutorialView)
code for readme:

```
[![Release](https://img.shields.io/github/release/itzikBraun/TutorialView.svg?label=JitPack)](https://jitpack.io/#itzikBraun/TutorialView)
```

**Comment by itzikBraun** [comment]
@jitpack-io  Thanks you, Added to the README.

@ajtoms Can you please reply and let me know if you need more help?
I want to know so I could close this issue.

Thanks, 
Itzik

**Comment by ajtoms** [comment]
I don't need any more help, you can close the issue. Thanks

**Comment by itzikBraun** [comment]
Thank you for making me finally doing it.
It's isn't in the readme file yet, But the library is in maven central and could be added using this line.

```
compile 'com.github.itzikbraun:TutorialView:0:8:1'
```
