### ISSUE TITLE
Not surrounding view in ViewPager

### ISSUE THREAD

**Issue by AizazZaidee** [itzikBraun/TutorialView#8]
How to make it work with FragmentActivity?

**Comment by itzikBraun** [comment]
Hi, 

Can you show me your code and what you tried so far? 

The best way for me to help you is by showing me some code so i could work with and maybe some images. You can also send me a sample project showing the problem and i would be happy to test.

**Comment by AizazZaidee** [comment]
I am sorry I removed the code now using another library because my classes are already extended with FragmentActivity and it was no working properly, it was not surrounding the views because on my screen there are different fragments.
