### ISSUE TITLE
Change "skip" and "got it" buttons text? 

### ISSUE THREAD

**Issue by Lir10** [itzikBraun/TutorialView#9]
Great lib!

Is ther any way to change the text of those buttons?

**Comment by itzikBraun** [comment]
Thank you, glad you liked it.

There are two ways to do that, One is to create your an XML resource string in your application module with the same id as the one used [here](https://github.com/itzikBraun/TutorialView/blob/master/tutorial_view/src/main/res/layout/skip_button_view.xml), This will override its value.

Second, Doing the same thing with the layout file for the got it button in your application, If they have the same name(Should also have the same id) then the application would use your version.

If you have any more questions let me know.

**Comment by itzikBraun** [comment]
Can i close this issue?
